# Generated by Django 4.2.1 on 2023-08-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_student', models.CharField(max_length=100)),
                ('Name_of_school', models.CharField(max_length=50)),
                ('Admission_number', models.CharField(max_length=30)),
                ('ID_card_number', models.DecimalField(decimal_places=0, max_digits=8)),
                ('Phone_number', models.DecimalField(decimal_places=0, max_digits=15)),
                ('Gender', models.CharField(max_length=10)),
                ('Form_or_Year', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
    ]
