# Generated by Django 4.2.1 on 2023-08-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_student', models.CharField(max_length=100)),
                ('name_of_school', models.CharField(max_length=50)),
                ('admission_number', models.CharField(max_length=30)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=15)),
                ('gender', models.CharField(max_length=10)),
                ('form_or_year', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('name_of_school', 'admission_number')},
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.DecimalField(decimal_places=0, max_digits=8, unique=True)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
